---
# This playbook installs Amazon Corretto JDK

- name: Install JDK
  gather_facts: false
  hosts: all
  vars:
    url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_windows_hotspot_8u242b08.msi
    file_name: "{{ url | basename }}"
    version: "{{ url.split('/')[7] }}"
  tasks:

    - debug:
        msg: "{{file_name}} {{version}}"

    - name: "Download AdoptOpenJDK [{{version}}] from {{url}}"
      win_get_url:
        follow_redirects: all
        force: no
        url: "{{url}}"
        dest: "C:\\{{file_name}}"

    - name: "Install AdoptOpenJDK"
      win_package:
        path: "C:\\{{file_name}}"